# ~/.config/starship.toml

# Inserts a blank line between shell prompts
add_newline = true

# Change command timeout from 500 to 1000 ms
command_timeout = 1000

# Change the default prompt format
# ---
# old config ...
#format = """\
#[╭╴](238)$env_var \
#$all[╰─](238)$character"""


# new config
format = '''
$env_var $time$directory$all'''


# Change the default prompt characters
[character]
# old config
# success_symbol = "[](238)"
# error_symbol = "[](238)"
success_symbol = "[£](white)"
error_symbol = "[£](red)"

# Shows an icon that should be included by zshrc script based on the distribution or os
[env_var.STARSHIP_DISTRO]
format = '[$env_value](#49be25)'
variable = "STARSHIP_DISTRO"
disabled = false

# Shows the username
[username]
style_user = "white bold"
style_root = "white"
format = "[$user]($style) "
disabled = true
show_always = true


[localip]
ssh_only = false
format = '@[$localipv4](bold red) '
disabled = true


[directory]
truncation_length = 3
truncation_symbol = "…/"
#home_symbol = " ~"
home_symbol = "~"
read_only_style = "197"
read_only = "  "
format = "[$path]($style)[$read_only]($read_only_style) "
style = "#676965"

[hostname]
ssh_only = false
format = "on [$hostname](bold yellow) "
disabled = true

[time]
disabled = false
format = '[$time]($style) '
time_format = '%T'
utc_time_offset = 'local'
style = "bold #49be25"


[git_branch]
symbol = " "
format = "via [$symbol$branch]($style) "
# truncation_length = 4
truncation_symbol = "…/"
style = "bold green"

[git_status]
format = '[\($all_status$ahead_behind\)]($style) '
style = "bold green"
conflicted = "🏳"
up_to_date = " "
untracked = " "
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
stashed = " "
modified = " "
staged = '[++\($count\)](green)'
renamed = "襁 "
deleted = " "

[kubernetes]
format = 'via [ﴱ $context\($namespace\)](bold purple) '
disabled = false

# (deactivated because of no space left)
# 
[terraform]
format = "via [ terraform $version]($style) 壟 [$workspace]($style) "
disabled = true

[vagrant]
format = "via [ vagrant $version]($style) "
disabled = true

[docker_context]
format = "via [ $context](bold blue) "
disabled = true

[helm]
format = "via [ $version](bold purple) "
disabled = true

[python]
symbol = " "
python_binary = "python3"
disabled = false

[nodejs]
format = "via [ $version](bold green) "
disabled = true

[ruby]
format = "via [ $version]($style) "
disabled = true
